services:
  app:
    container_name: "basic-app"
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - nodejs-service
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    user: postgres
    image: postgres:${POSTGRES_VERSION}
    container_name: "node-gmp-db"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - nodejs-service

networks:
  nodejs-service:
    driver: bridge
    name: rsschool-nodejs-bridge
